<?php
/**
 * Template for displaying restricted countries
 */

// echo 'hihihihooooooooooooo';

$block = $this->getLayout()->getBlock('restrictedcountries');

$restrictedCountries = $block->getRestrictedCountries();

//echo $restrictedCountries;

//dd($restrictedCountries);
// echo 'Country is'.$restrictedCountries;

if ($restrictedCountries) {
    echo '<div class="restricted-countries">';
    echo '<strong>Restricted Countries:</strong> ' . $block->escapeHtml($restrictedCountries);
    echo '</div>';
}
else{
    echo 'Nothing found';
}
