<form action="<?php echo $block->getUrl('customform/index/submit'); ?>" method="post" enctype="multipart/form-data">
    <label>First Name:</label>
    <input type="text" name="first_name" required /><br/><br/>

    <label>Last Name:</label>
    <input type="text" name="last_name" required /><br/><br/>

    <label>Email:</label>
    <input type="email" name="email" required /><br/><br/>

    <label>Phone Number:</label>
    <input type="text" name="phone_number" required /><br/><br/>

    <label>Image:</label>
    <input type="file" name="image" /><br/><br/>

    <button type="submit">Submit</button>
</form>

