<!--<form id="edit_form" action="--><?php //= $block->getUrl('grid/index/save') ?><!--" method="post">-->
<!--    <input type="hidden" name="form_key" value="--><?php //= $block->getFormKey(); ?><!--" />-->
<!--    <fieldset>-->
<!--        <div class="admin__field">-->
<!--            <label class="admin__field-label" for="title">--><?php //= __('Title') ?><!--</label>-->
<!--            <div class="admin__field-control">-->
<!--                <input type="text" name="title" id="title" required>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="admin__field">-->
<!--            <label class="admin__field-label" for="description">--><?php //= __('Description') ?><!--</label>-->
<!--            <div class="admin__field-control">-->
<!--                <textarea name="description" id="description" required></textarea>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--        <div class="actions">-->
<!--            <button type="submit" class="action-save primary">-->
<!--                --><?php //= __('Update') ?>
<!--            </button>-->
<!--        </div>-->
<!--    </fieldset>-->
<!--</form>-->
