<?php
$data = $block->getPosts();
//print_r($data);
?>

<style>
    .blog-container {
        width: 80%;
        margin: 0 auto;
        padding: 20px;
    }
    .blog {
        border: 1px solid #ddd;
        padding: 15px;
        margin-bottom: 20px;
        border-radius: 5px;
    }
    .blog-title {
        font-size: 1.5em;
        margin-bottom: 10px;
    }
    h2 {
        font-weight: bold;
    }
    .blog-content {
        font-size: 1em;
        margin-bottom: 15px;
    }
</style>


<div class="blog-container">
    <?php foreach ($data as $posts): ?>
        <div class="blog">
            <h2 class="blog-title"><?= ($posts['title']) ?></h2>
            <p class="blog-content"><?= ($posts['content']) ?></p>
            <?php
            $imageFileName = $posts->getImage();
            if ($imageFileName) {
                $imageUrl = $block->getBaseUrl() . 'pub/media/test/' . htmlspecialchars($imageFileName);
                echo '<img src="' . $imageUrl . '" alt="image" width="150"/>';
            } else {
                echo '<p>No image available.</p>';
            }?>
        </div>
    <?php endforeach; ?>

    <!-- Pagination Links -->
    <?php if ($block->getTotalPages() > 1): ?>
        <div class="pagination">
            <!-- Previous Button -->
            <?php if ($block->getData('currentPage') > 1): ?>
                <button>
                    <a href="#" class="pagination-link" data-page="<?= $block->getData('currentPage') - 1 ?>">Previous</a>
                </button>
            <?php endif; ?>

            <!-- Page Numbers -->
            <?php for ($i = 1; $i <= $block->getTotalPages(); $i++): ?>
                <button>
                    <a href="#" class="pagination-link <?= $i == $block->getData('currentPage') ? 'active' : '' ?>" data-page="<?= $i ?>"><?= $i ?></a>
                </button>
            <?php endfor; ?>

            <!-- Next Button -->
            <?php if ($block->getData('currentPage') < $block->getTotalPages()): ?>
                <button>
                    <a href="#" class="pagination-link" data-page="<?= $block->getData('currentPage') + 1 ?>">Next</a>
                </button>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
